apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: prompt-processing2
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  #replica:
  #  enabled: false
  #  source: old-prompt-processing

  imageName: ghcr.io/lsst-sqre/cnpg-postgres-images:17.5
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true'

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    parameters:
      jit: "off"
      shared_buffers: 2GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      max_connections: "2000"
      log_disconnections: "on"
      log_duration: "on"
      log_statement: all
      log_min_duration_statement: 250ms

  resources:
    requests:
      memory: 16Gi
      cpu: 8
    limits:
      memory: 32Gi
      cpu: 16

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 1500Gi
    resizeInUseVolumes: False
